#SPRINT 7

##NIVEL 1

###**EJERCICIO 1**

**Selección de personal** Tu treballes com a analista de dades en el departament de RRHH d'una empresa. S'ha obert una nova oferta laboral interna i l'empresa ha decidit que només les primeres 10 persones que s'inscriguin podran participar en el procés de selecció.

Per això, t'han encarregat desenvolupar una eina senzilla en Python que actuï com a formulari d'inscripció i sistema de classificació inicial. Aquest formulari ha de permetre introduir, per a cada candidat/a:

- Nom i Cognoms
- Telèfon de contacte
- Anys d'experiència dins de l'empresa
- Coneixement de Català (0–3 punts)
0 = sense coneixement
1 = fins a nivell B1
2 = nivell B2
3 = C1 o superior
- Domini d'Excel (0–3 punts)
0 = nivell bàsic
1 = ús de funcions
2 = taules dinàmiques
3 = Visual Basic i Macros
- Títol acadèmic (0–3 punts)
0 = ESO
1 = FP
2 = Universitat
3 = Màster o superior

Assegurant-se que tota la informació introduïda és correcta i entra dins els valors permesos. A partir d'aquestes dades, el programa haurà de calcular una puntuació total aplicant el pes de l'experiència (anys * 1.5) i sumant-hi els punts de català, excel i titulació, i a continuació classificar automàticament cada persona segons els llindars establerts per l'empresa:

- Prioritat Alta → puntuació ≥ 12
- Candidat adequat → 8 ≤ puntuació < 12
- No prioritari → puntuació < 8

Cada vegada que algú complet a el formulari, s'ha de mostrar la seva puntuació individual. Quan ja s'hagin inscrit exactament deu persones, l'eina ha de deixar d'acceptar nous registres i generar un informe final en pantalla, ordenat primer segons la prioritat i, en cas d'empat, per la puntuació obtinguda. Aquest informe ha d'incloure el nom, el telèfon i la puntuació de cada candidat per tal que el departament de RRHH els pugui contactar ràpidament.

**ESTRUCUTURA ALGORITMO**

Para esta estrucutra, realizo varias funciones (modularidad) que recogeran los datos y que comporbaran que este correctos, asi como se presentarán los datos obtenidos, por candidato y se muestra un informe final de todos los candidatos.

Para ello defino una seria de funciones, donde cada una de ellas realizará un proceso distinto.


1.   Función datos_candidato: En esta función se solicita una seria de datos. Se recogen mediante inputs y se guardan en un diccionario. La información de cada candidato será retornado en un diccionario, que se guardará en una lista, más adelante en la funcion proceso seleccion.

2.   Función validación nombre: Función que se encarga de revisar y validar que el nombre este correctamente definido como nombre y apellido.
La función recoge en su parametro de entrada el diccionario para analizar el valor de la clave nombre. Lo retorna revisado y modificado si es el caso.

3.  Función validación telefono: Función que se encarga de revisar y validar el número de telefono facilitado. Este debe de estar dentro de los parametros, sin espacios ni simbolos.
La función recoge en su parametro de entrada el diccionario para analizar el valor de la clave telefono. Lo retorna revisado y modificado si es el caso.

4.  Función validación experiencia: Función que se encarga de revisar y validar que se hay introducido un valor númerico entero para los años trabajados en la empresa.
La función recoge en su parametro de entrada el diccionario para analizar el valor de la clave expereincia. Lo retorna revisado y modificado si es el caso.

5.  Función validación niveles: Función que revisa que los datos facilitados para puntuar los niveles de conocimiento en catalán, excel y nivel de educación acabado.
La función recoge en su parametro de entrada el diccionario para analizar el valor de cada clave de conocimiento. Lo retorna revisado y modificado si es el caso.

6. Todas las validaciones estan recogidas en la función validaciones.

7. Función calcular puntuación: Se encarga de calcular, la puntuacion total de cada candidato, tomando los valores de experiencia (años trabajados * 1.5), y nivel adquirido en catalan, excel y titulo univeristario. sumados.
La función recoge en su parametro de entrada el diccionario para analizar el valor de cada clave solicitada. Lo retorna con la nueva pareja K:V.

8. Función clasificación candidatos: Se clasifica a los candidatos según la puntuación obtenida en la función anterior y según los parámetros establecidos en el enunciado. Se añade a cada candidato dos nuevos campos, uno con la clasificación redactada y otro con la clasificación numérica asociada.
La función recoge en su parametro de entrada el diccionario. Lo retorna con dos nuevas parejas K:V.

9. Función solicitud candidato: Muestra a cada candidato la información facilitada así como su puntuacion final.
La funcion tiene como parametro, el contador, para que se sepa en que posición está y el diccionario con su información. No retorna nada, puesto que la informacion no se ha modificado, solo imprime resultados.

10. Función informe RRHH: Función que recoge la lista de diccionarios (que se genera en la función principal), donde cada diccionario contiene la información de un candidato. Ordena a todos los candidatos por prioridad y puntuación.
Imprime la información que solicita el departamento en orden.

11. Funcion proceso de selección: Es la función principal donde se orquestan el resto de funciones. Hay un contador, que permite, gracias a un bucle, aceptar 10 solicitudes, si esta dentro de la condicion, procesa las anteriores funcione, menos la del informa RRHH.
Al llegar a 10 candidaturas el bucle se para mosntrando antes el informe de RRHH que se genera en la anterior función.

añadir argunmentos
llamar cada funbcion individual

In [ ]:
def datos_candidato ():
  """
  Funcion en la que se toman los datos posolicitados por RRHH para optar por la nueva posción.

  Sin argumentos. Solicita info dentro.
  Retorna un diccionario con la informacion solicitada.
  """
  # para que no de error al introducir datos, toda respuesta sera un string y despues en la comprobacaion se haran distintos expcepts
  resultado = {}
  print("Iniciamos la toma de datos para formalizar su candidatura.\nPor favor, responda las siguientes preguntas:\n")

  resultado["nombre"] = input("1. Cual es su nombre y apellido: \n") #aqui a la hora de validar que sea correcto puedo comprobar que haya espacio en blanco, sino los hay se rechaza
  resultado["telefono"] = input("\n2. Cual es su numero de telefono: \n") #aqui pongo que los caracteres deben de ser de entre 12 y 9 para confirmar que hay nuemero de telefono
  resultado["experiencia"] = input("\n3. Cuantos años de experiencia tiene en la empresa?\n"+
                                   "Redondé al año entero.\n")
  resultado["catalan"] =  input("\n4. Quen nivel de catalan tiene?:\n\n"+
                                "0 - Sin conocimiento.\n1 - Hasta el B1.\n2 - Hasta el nivel B2.\n3 - C1 o superior.\n"+
                                "Por favor, introduzca el número de su nivel.\n "
   )
  resultado["excel"] = input("\n5. Que nivel de excel tiene?:\n\n"+
                             "0 - Nivel básico.\n1 - Uso de funciones.\n2 - Uso tablas dinámicas.\n3 - Visual Basic y Macros.\n"+
                             "Por favor, introduzca el número de su nivel.\n"
  )
  resultado["titulo"] = input("\n6. Cual es su último título academica?:\n\n"+
                              "0 - ESO.\n1 - FP.\n2 - Universidad.\n3 - Máster o superior.\n\n"+
                              "Por favor, introduzca el número de su nivel.\n")
  return resultado

In [ ]:
#prueba de la funcion:
datos_candidato()

Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Leticia de Cuevillas

2. Cual es su numero de telefono:
1111112114

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
5

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 3

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
3

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
3

{'nombre': 'Leticia de Cuevillas',
 'telefono': '1111112114',
 'experiencia': '5',
 'catalan': '3',
 'excel': '3',
 'titulo': '3'}

In [ ]:
def validacion_nombre (respuestas_candidatos):
  """
  Función para validar que el nombre contenga nombre y apellidos, sin números ni simbolos.

  Argumeno recibido: Diccionario con la información del candidato.
  Retorna el mismo diccionario validado y modificado de ser necesario.
  """
  nombre_comprobar = respuestas_candidatos["nombre"]
  while True:
    try:
      if len(nombre_comprobar.split()) < 2:
        raise ValueError(
            f"El nombre introducido {nombre_comprobar} no es valido.\n"
            "Debe facilitar un nombre y apellido.\n"
        )
      if any(letra.isdigit() for letra in nombre_comprobar):
        raise ValueError(
            f"El nombre introducido {nombre_comprobar} no es valido."
            "Su nombre no puede contener números.\n"
        )
      respuestas_candidatos["nombre"] = nombre_comprobar
      return respuestas_candidatos
    except ValueError as e:
      print(f"\nError: {e}")
      nombre_comprobar = input("Por favor, introduzca su nombre y apellido nuevamente:\n")

In [ ]:
def validacion_telefono (respuestas_candidatos):
  """
  Función para validar que el número de telefono sea correcto.

  Argumeno recibido: Diccionario con la información del candidato.
  Retorna el mismo diccionario validado y modificado de ser necesario.
  """
  telefono = respuestas_candidatos["telefono"]
  while True:
    try:
      telefono = str(telefono).replace(" ", "").replace("-", "").replace(".","").replace(",", "")
      if not telefono.isdigit():
        raise ValueError (
            f"Su telefono número: {telefono}, no es valido"
            "debe contener solo digitos\n"
        )
      if len(telefono) < 9 or len(telefono) > 12:
        raise ValueError(
            f"Su telefono número: {telefono} debe tener entre 9 y 12 digitos\n"
            )
      respuestas_candidatos["telefono"] = telefono
      return respuestas_candidatos
    except ValueError as e:
      print(f"\nError: {e}")
      telefono = input("Por favor, introduzca su numero de telefono nuevamente:\n")

In [ ]:
def validacion_experiencia (respuestas_candidatos):
  """
  Función para validar que el número de años trabajados en la empresa
  sea un número entero.

  Argumeno recibido: Diccionario con la información del candidato.
  Retorna el mismo diccionario validado y modificado de ser necesario.
  """
  experiencia = respuestas_candidatos["experiencia"]
  while True:
    try:
      if isinstance(experiencia, str):
        try:
          experiencia = float(experiencia)
        except ValueError:
          raise ValueError(
              f"No se permite texto en el campo Experiencia.\n"
              "Debe facilitar un número entero redondeado de años trabajados en la empresa.\n"
          )
      if isinstance(experiencia, float) and not experiencia.is_integer():
        raise ValueError(
            f"No se permiten números con decimales en el campo Experiencia como {experiencia}.\n"
            "Debe facilitar un número entero redondeado de años trabajados en la empresa.\n"
        )
      experiencia = int(experiencia)
      if experiencia < 0:
        raise ValueError(
            "Debe presentar años positivos trabajados en la empresa.\n"
            )
      respuestas_candidatos["experiencia"] = experiencia
      return respuestas_candidatos
    except ValueError as e:
      print(f"\nError: {e}")
      experiencia = input("Por favor, introduzca el número de nuevo:\n ")

In [ ]:
def validacion_niveles(respuestas_candidatos):
  """
  Funcion para validar que los datos referentes a la experiencia en los campos:
  Catalán, Excel y titulacion academica esten dentro de los parámetros.

  Argumeno recibido: Diccionario con la información del candidato.
  Retorna el mismo diccionario validado y modificado de ser necesario.
   """
  for tema, nota in [("catalan", respuestas_candidatos["catalan"]),
                     ("excel", respuestas_candidatos["excel"]),
                     ("titulo", respuestas_candidatos["titulo"])]:
    while True:
      try:
        if not nota.isdigit():
          raise ValueError(
              f" El valor: {nota}, en el campo {tema} no es valido.\n"
              "No se permite texto ni simbolos. Debe introducir un número entre el 0 y el 3 .\n"
              )
        nota = int(nota)
        if nota not in [0, 1, 2, 3]:
          raise ValueError(
              f"El valor: {nota}, en el campo {tema} está fuera de parametros.\n"
              "Debe introducir un número entre el 0 y el 3.\n"
              )
        respuestas_candidatos[tema] = nota
        break
      except ValueError as e:
        print(f"\nError: {e}")
        nota = input(f"Por favor, introduzca su nivel de {tema} nuevamente:\n")

  return respuestas_candidatos

In [ ]:
def validaciones (respuestas_candidatos):
  """
  Funcion que unifica las validaciones de los campos solicitados por RRHH.

  Argumeno recibido: Diccionario con la información del candidato.
  Retorna el mismo diccionario validado y modificado de ser necesario.
  """
  validacion_nombre(respuestas_candidatos)
  validacion_telefono(respuestas_candidatos)
  validacion_experiencia(respuestas_candidatos)
  validacion_niveles(respuestas_candidatos)

  return respuestas_candidatos

In [ ]:
#prueba de la funcion:
#Con todos los datos mal
datos_prueba_inc = {'nombre': 'Leticia',
 'telefono': '1111',
 'experiencia': '5.4',
 'catalan': '7',
 'excel': '10',
 'titulo': 's'}

validaciones(datos_prueba_inc)

Error: El nombre introducido Leticia no es valido.
Debe facilitar un nombre y apellido.

Por favor, introduzca su nombre y apellido nuevamente:
Leticia de Cuevillas

Error: Su telefono número: 1111 debe tener entre 9 y 12 digitos

Por favor, introduzca su numero de telefono nuevamente:
1111111111111

Error: Su telefono número: 1111111111111 debe tener entre 9 y 12 digitos

Por favor, introduzca su numero de telefono nuevamente:
123456789

Error: No se permiten números con decimales en el campo Experiencia como 5.4.
Debe facilitar un número entero redondeado de años trabajados en la empresa.

Por favor, introduzca el número de nuevo:
 5

Error: El valor: 7, en el campo catalan está fuera de parametros.
Debe introducir un número entre el 0 y el 3.

Por favor, introduzca su nivel de catalan nuevamente:
3

Error: El valor: 10, en el campo excel está fuera de parametros.
Debe introducir un número entre el 0 y el 3.

Por favor, introduzca su nivel de excel nuevamente:
3

Error:  El valor: s, en el campo titulo no es valido.
No se permite texto ni simbolos. Debe introducir un número entre el 0 y el 3 .

Por favor, introduzca su nivel de titulo nuevamente:
2

{'nombre': 'Leticia de Cuevillas',
 'telefono': '123456789',
 'experiencia': 5,
 'catalan': 3,
 'excel': 3,
 'titulo': 2}

In [ ]:
def calcular_puntuacion (respuestas_candidatos):
  """
  Funcion para calcular la puntuacion de cada candidato

  Argumento recibido: Diccionario con la información del candidato.
  Retorna el mismo diccionario con nueva clave "puntuacion y su valor calculado.
  """
  puntuaciones = (respuestas_candidatos["experiencia"] * 1.5 +
                respuestas_candidatos["catalan"] +
                respuestas_candidatos["excel"] +
                respuestas_candidatos["titulo"])
  respuestas_candidatos["puntuacion"] = puntuaciones

  return respuestas_candidatos

In [ ]:
#Prueba función:
datos_prueba = {'nombre': 'Leticia de Cuevillas',
 'telefono': '123456789',
 'experiencia': 5,
 'catalan': 3,
 'excel': 3,
 'titulo': 2}

calcular_puntuacion(datos_prueba)

{'nombre': 'Leticia de Cuevillas',
 'telefono': '123456789',
 'experiencia': 5,
 'catalan': 3,
 'excel': 3,
 'titulo': 2,
 'puntuacion': 15.5}

In [ ]:
def clasificacion_candidato (respuestas_candidatos):
  """
  Función para clasificar a cada candidato según su puntuación.

  Argumento recibido: Diccionario con la información del candidato.
  Retorna el mismo diccionario con dos nuevas claves "clasificacion" y
  "posición clasificación" y sus valores.
  """
  clasificacion = ""
  posicion_clasificacion = 0
  if respuestas_candidatos["puntuacion"] >=  12:
      clasificacion = "Prioridad Alta"
      posicion_clasificacion = 1
  elif respuestas_candidatos["puntuacion"] >= 8:
      clasificacion = "Candidato Adecuado"
      posicion_clasificacion = 2
  else:
      clasificacion = "No prioritario"
      posicion_clasificacion = 3
  respuestas_candidatos["clasificacion"] = clasificacion
  respuestas_candidatos["posicion_clasificacion"] = posicion_clasificacion

  return respuestas_candidatos

In [ ]:
datos_prueba2 = {'nombre': 'Leticia de Cuevillas',
 'telefono': '123456789',
 'experiencia': 5,
 'catalan': 3,
 'excel': 3,
 'titulo': 2,
 'puntuacion': 15.5}

clasificacion_candidato(datos_prueba2)

{'nombre': 'Leticia de Cuevillas',
 'telefono': '123456789',
 'experiencia': 5,
 'catalan': 3,
 'excel': 3,
 'titulo': 2,
 'puntuacion': 15.5,
 'clasificacion': 'Prioridad Alta',
 'posicion_clasificacion': 1}

In [ ]:
def solicitud_candidato(contador, respuestas_candidatos):
    """
    Funcion que recoge las respuestas del candidato y las muestra en pantalla.

    Argumentos recibidos:
      1. Contador para establecer nº de solicitud.
      2. Dicionario con la información del candidato.
    No retorna nada ya que lo imprime en pantalla.
    """
    print(f"\nHa realizado la solicitd nº {contador} con los siguintes datos:\n"+
        f"Nombre y apellido: {respuestas_candidatos['nombre']}.\n"+
        f"Teléfono: {respuestas_candidatos['telefono']}.\n"+
        f"Años trabajados en la empresa: {respuestas_candidatos['experiencia']} años.\n"+
        f"Nivel de conocimiento en Catalán: {respuestas_candidatos['catalan']}.\n"+
        f"Nivel de conocimiento en Excel: {respuestas_candidatos['excel']}.\n"+
        f"Ha obtenido una puntuación final de: {respuestas_candidatos['puntuacion']} puntos.\n\n"+
        "Se le contactara proximamente desde el departamento de Recursos Humanos.\n\n")

In [ ]:
#Prueba de función
datos_prueba3 = {'nombre': 'Leticia de Cuevillas',
 'telefono': '123456789',
 'experiencia': 5,
 'catalan': 3,
 'excel': 3,
 'titulo': 2,
 'puntuacion': 15.5,
 'clasificacion': 'Prioridad Alta',
 'posicion_clasificacion': 1}

solicitud_candidato(1, datos_prueba3)

Ha realizado la solicitd nº 1 con los siguintes datos:
Nombre y apellido: Leticia de Cuevillas.
Teléfono: 123456789.
Años trabajados en la empresa: 5 años.
Nivel de conocimiento en Catalán: 3.
Nivel de conocimiento en Excel: 3.
Ha obtenido una puntuación final de: 15.5 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.

In [ ]:
def informa_rrhh(candidatos):
  """
  Función que prepara el informe solicitado por RRHH, ordena los candidatos por
  la posición en la clasificación y, de haber empate, por su puntuación.

  Argumento recibido con la lista de diccionarios de los 10 candidatos aceptados.
  No devuelve nada, imprime toda la información.
  """
  resultados_ordenados = sorted(
      candidatos, key = lambda x: (x["posicion_clasificacion"], -x["puntuacion"])
      )
  print("Informe de candidatos:\n")
  for candidato in resultados_ordenados:
    print(f"Nombre y apellido: {candidato['nombre']}.\n"+
          f"Teléfono: {candidato['telefono']}.\n"+
          f"Puntuación final: {candidato['puntuacion']}.\n\n")

In [ ]:
#Prueba función:
lista_prueba = [{'nombre': 'Leticia de Cuevillas',
 'telefono': '123456789',
 'experiencia': 5,
 'catalan': 3,
 'excel': 3,
 'titulo': 2,
 'puntuacion': 15.5,
 'clasificacion': 'Prioridad Alta',
 'posicion_clasificacion': 1},
  {'nombre': 'Jesus Perez',
 'telefono': '9876543210',
 'experiencia': 1,
 'catalan': 3,
 'excel': 2,
 'titulo': 3,
 'puntuacion': 7,
 'clasificacion': 'Prioridad baja',
 'posicion_clasificacion': 3}]

informa_rrhh(lista_prueba)

Informe de candidatos:

Nombre y apellido: Leticia de Cuevillas.
Teléfono: 123456789.
Puntuación final: 15.5.


Nombre y apellido: Jesus Perez.
Teléfono: 9876543210.
Puntuación final: 7.

In [ ]:
def proceso_seleccion():
  """
  Función que dirige las acciones según solicitudes recibidas.

  No recibe ni retorna nada.
  """
  lista_candidatos = []
  contador = 1
  while True:
    if contador <= 10 :
        respuestas_candidatos = datos_candidato() #Se obtienen info de los candidatos
        respuestas_validadas = validaciones(respuestas_candidatos) #Se valida info
        resultados_calculados = calcular_puntuacion(respuestas_validadas) #Se calcula puntuacion
        resultados_clasificados = clasificacion_candidato (resultados_calculados)  #se hace la clasificacion del candidato
        solicitud_candidato(contador, resultados_clasificados) #informe para el candidato
        lista_candidatos.append(resultados_clasificados)
        contador += 1
    else:
        informa_rrhh(lista_candidatos)
        print("Ya no se aceptan más solicitudes")
        break

In [ ]:
proceso_seleccion()

Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Laura Serra

2. Cual es su numero de telefono:
608112233

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
6

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 3

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
3

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
3

Ha realizado la solicitd nº 1 con los siguintes datos:
Nombre y apellido: Laura Serra.
Teléfono: 608112233.
Años trabajados en la empresa: 6 años.
Nivel de conocimiento en Catalán: 3.
Nivel de conocimiento en Excel: 3.
Ha obtenido una puntuación final de: 18.0 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Clara Gómez

2. Cual es su numero de telefono:
655221199

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
3

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 3

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
3

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
2

Ha realizado la solicitd nº 2 con los siguintes datos:
Nombre y apellido: Clara Gómez.
Teléfono: 655221199.
Años trabajados en la empresa: 3 años.
Nivel de conocimiento en Catalán: 3.
Nivel de conocimiento en Excel: 3.
Ha obtenido una puntuación final de: 12.5 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Sergio López

2. Cual es su numero de telefono:
644112211

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
3

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 2

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
2

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
2

Ha realizado la solicitd nº 3 con los siguintes datos:
Nombre y apellido: Sergio López.
Teléfono: 644112211.
Años trabajados en la empresa: 3 años.
Nivel de conocimiento en Catalán: 2.
Nivel de conocimiento en Excel: 2.
Ha obtenido una puntuación final de: 10.5 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Candidat Error

2. Cual es su numero de telefono:
611000000

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
5

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 7

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
3

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
2

Error: El valor: 7, en el campo catalan está fuera de parametros.
Debe introducir un número entre el 0 y el 3.

Por favor, introduzca su nivel de catalan nuevamente:
2

Ha realizado la solicitd nº 4 con los siguintes datos:
Nombre y apellido: Candidat Error.
Teléfono: 611000000.
Años trabajados en la empresa: 5 años.
Nivel de conocimiento en Catalán: 2.
Nivel de conocimiento en Excel: 3.
Ha obtenido una puntuación final de: 14.5 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Marta Ruiz

2. Cual es su numero de telefono:
699887766

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
2

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 3

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
2

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
1

Ha realizado la solicitd nº 5 con los siguintes datos:
Nombre y apellido: Marta Ruiz.
Teléfono: 699887766.
Años trabajados en la empresa: 2 años.
Nivel de conocimiento en Catalán: 3.
Nivel de conocimiento en Excel: 2.
Ha obtenido una puntuación final de: 9.0 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Marc Vidal

2. Cual es su numero de telefono:
612443322

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
6

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 3

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
3

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
3

Ha realizado la solicitd nº 6 con los siguintes datos:
Nombre y apellido: Marc Vidal.
Teléfono: 612443322.
Años trabajados en la empresa: 6 años.
Nivel de conocimiento en Catalán: 3.
Nivel de conocimiento en Excel: 3.
Ha obtenido una puntuación final de: 18.0 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Júlia Romero

2. Cual es su numero de telefono:
677998877

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
5

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 3

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
3

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
2

Ha realizado la solicitd nº 7 con los siguintes datos:
Nombre y apellido: Júlia Romero.
Teléfono: 677998877.
Años trabajados en la empresa: 5 años.
Nivel de conocimiento en Catalán: 3.
Nivel de conocimiento en Excel: 3.
Ha obtenido una puntuación final de: 15.5 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Pol Navarro

2. Cual es su numero de telefono:
699554433

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
4

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 3

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
2

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
2

Ha realizado la solicitd nº 8 con los siguintes datos:
Nombre y apellido: Pol Navarro.
Teléfono: 699554433.
Años trabajados en la empresa: 4 años.
Nivel de conocimiento en Catalán: 3.
Nivel de conocimiento en Excel: 2.
Ha obtenido una puntuación final de: 13.0 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
David Ferrer

2. Cual es su numero de telefono:
677665544

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
2

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 1

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
1

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
1

Ha realizado la solicitd nº 9 con los siguintes datos:
Nombre y apellido: David Ferrer.
Teléfono: 677665544.
Años trabajados en la empresa: 2 años.
Nivel de conocimiento en Catalán: 1.
Nivel de conocimiento en Excel: 1.
Ha obtenido una puntuación final de: 6.0 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Iniciamos la toma de datos para formalizar su candidatura.
Por favor, responda las siguientes preguntas:

1. Cual es su nombre y apellido:
Anna Paredes

2. Cual es su numero de telefono:
633221144

3. Cuantos años de experiencia tiene en la empresa?
Redondé al año entero.
1

4. Quen nivel de catalan tiene?:

0 - Sin conocimiento.
1 - Hasta el B1.
2 - Hasta el nivel B2.
3 - C1 o superior.
Por favor, introduzca el número de su nivel.
 2

5. Que nivel de excel tiene?:

0 - Nivel básico.
1 - Uso de funciones.
2 - Uso tablas dinámicas.
3 - Visual Basic y Macros.
Por favor, introduzca el número de su nivel.
1

6. Cual es su último título academica?:

0 - ESO.
1 - FP.
2 - Universidad.
3 - Máster o superior.

Por favor, introduzca el número de su nivel.
0

Ha realizado la solicitd nº 10 con los siguintes datos:
Nombre y apellido: Anna Paredes.
Teléfono: 633221144.
Años trabajados en la empresa: 1 años.
Nivel de conocimiento en Catalán: 2.
Nivel de conocimiento en Excel: 1.
Ha obtenido una puntuación final de: 4.5 puntos.

Se le contactara proximamente desde el departamento de Recursos Humanos.


Informe de candidatos:

Nombre y apellido: Laura Serra.
Teléfono: 608112233.
Puntuación final: 18.0.


Nombre y apellido: Marc Vidal.
Teléfono: 612443322.
Puntuación final: 18.0.


Nombre y apellido: Júlia Romero.
Teléfono: 677998877.
Puntuación final: 15.5.


Nombre y apellido: Candidat Error.
Teléfono: 611000000.
Puntuación final: 14.5.


Nombre y apellido: Pol Navarro.
Teléfono: 699554433.
Puntuación final: 13.0.


Nombre y apellido: Clara Gómez.
Teléfono: 655221199.
Puntuación final: 12.5.


Nombre y apellido: Sergio López.
Teléfono: 644112211.
Puntuación final: 10.5.


Nombre y apellido: Marta Ruiz.
Teléfono: 699887766.
Puntuación final: 9.0.


Nombre y apellido: David Ferrer.
Teléfono: 677665544.
Puntuación final: 6.0.


Nombre y apellido: Anna Paredes.
Teléfono: 633221144.
Puntuación final: 4.5.


Ya no se aceptan más solicitudes

Dandole vueltas a la función, no le veia mucho sentido hacer un código con bucle while, pues al llamar a la función si o si se han de rellenar todas las solicitudes hasta llegar al limite. He querido ver como sería, si se pudiera llamar a la función cada vez que un candidato quisiera realizar una solicitud.
Las siguientes celdas de codigo son las funciones que he adaptado para poder realizar la ejecución de mi idea.

In [ ]:
#Si se hace llamando a la funcion las x veces necesarias
"""def solicitud_candidato(contador):
  """
  #Funcion que recoge las respuestas del candidato y las muestra en pantalla.
  #Cuando se han inscrito 10 retorna el lista con la informacion de los candidatos.
"""contador = contador
  respuestas_candidatos = datos_candidato() #Se obtienen info de los candidatos
  respuestas_validadas = validaciones(respuestas_candidatos) #Se valida info
  resultados_calculados = calcular_puntuacion(respuestas_validadas) #Se calcula puntuacion
  resultados_clasificados = clasificacion_candidato (resultados_calculados)  #se hace la clasificacion del candidato
  print(f"\nHa realizado la solicitd nº {contador} con los siguintes datos:\n"+
        f"Nombre y apellido: {respuestas_candidatos['nombre']}.\n"+
        f"Teléfono: {respuestas_candidatos['telefono']}.\n"+
        f"Años trabajados en la empresa: {respuestas_candidatos['experiencia']} años.\n"+
        f"Nivel de conocimiento en Catalán: {respuestas_candidatos['catalan']}.\n"+
        f"Nivel de conocimiento en Excel: {respuestas_candidatos['excel']}.\n"+
        f"Ha obtenido una puntuación final de: {respuestas_candidatos['puntuacion']} puntos.\n\n"+
        "Se le contactara proximamente desde el departamento de Recursos Humanos.\n\n")
  contador += 1
  return contador, resultados_clasificados"""

In [ ]:
# Si se hace llamando a la función cada vez que un candidato quiera aplicar:
"""def proceso_seleccion(contador_int, lista):
  """
  #Funcion que dirige las acciones segun solicitudes recibidas.
"""
  lista_candidatos = lista
  contador = contador_int
  if contador < 10:
      contador, respuestas = solicitud_candidato(contador)
      lista_candidatos.append(respuestas)
  elif contador == 10:
      contador, respuestas = solicitud_candidato(contador)
      lista_candidatos.append(respuestas)
      informa_rrhh(lista_candidatos)
      contador += 1
  else:
    print("No se aceptan más solicitudes")
    contador += 1
  return contador, lista_candidatos"""

In [ ]:
# Si se hace llamando a la función cada vez que un candidato quiera aplicar:
"""contador = 1 #empiezo contador por 1 porque sino empieza a iterar en rango 0 y permite hasta 11 solicitudes
lista_candidatos = []
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
contador, lista_candidatos = proceso_seleccion(contador, lista_candidatos)
print (contador)"""

### **EJERCICIO 2**

**Segmentació per risc de cistella de compra**

Treballes com a analista de dades al departament de Màrqueting Digital. L'empresa vol millorar l'efectivitat de les campanyes de recuperació de cistellas de compra abandonats i necessita identificar quins clients tenen més risc d'abandonament, quin segment de comportament presenten i quin missatge publicitari és el més adequat per a cadascun.
Disposes d'un conjunt de dades amb informació bàsica de 10 clients:

id_client
nom
edat
grup_edat
codi_comportament

El departament de CRM ha definit manualment:

- Codis de comportament
  - 0 → Navega però no afegeix productes
  - 1 → Afegeix productes però no arriba al checkout
  - 2 → Arriba al checkout però no paga
  - 3 → Cistella de compra abandonat fa menys de 24 h
  - 4 → Cistella de compra abandonat fa més de 24 h
- Factors segons codi de comportament
  - Codi 0 → 0.10
  - Codi 1 → 0.25
  - Codi 2 → 0.50
  - Codi 3 → 0.75
  - Codi 4 → 0.90
- Factors segons grup d'edat
  - 18–25 → 1.20
  - 26–40 → 1.00
  - 41–60 → 0.85
  - 60+ → 0.70
- Fórmula del risc final
risc_final = factor codi * factor edat

Un cop processats els clients, has de ser capaç de respondre:

- 1. Quins clients s'han de contactar primer en una campanya de retargeting?
- 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?).
- 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost? -
- 4. Quin client seria el més rendible de recuperar?
Interpretant el risc final i el segment.

**ESTRUCTURA ALGORITMO**

1. Función procesar clientes: Funcion que toma la lista de diccionarios facilitada por el departamento, la convierte en un diccionario de diccionarios, donde cada diccionario principal es el id de cliente y su valor el resto de información del cliente. Así mismo, se amplia los datos del cliente que se gestionan en las tres siguientes funciones. Retorna el diccionario de diccionarios con los datos de los clientes.

2. Función obtener segmento y factor: Función que devuelve las claves y valores con los datos de segmento, mensaje publicitario y factor comportamiento correctamente asignado según el codigo_comportamiento, establecido como parametro de la función.

3. Función obtener factor edad: Función que devuelve el valor de los datos de factor edad, correctamente asignado según el grupo edad que se establece como parametro de la función.

4. Función calcular riesgo: Función que calcula el riesgo del cliente según el codigo de riesgo y la edad. Retorna el valor del calculo, que se establece como valor de la clave riesgo final en la función procesar cliente.

5. Función mostrar df: Recoge en los parametros el diccionario de diccionarios y lo convierte en un DataFrame que lo retorna. Se establece el id_cliente como indice y se cambian los nombres de las columnas en castellano.

6. Función mostrar_respuestas: Función que calcula las respuestas a las preguntas realizadas por el departamento y las muestra. Toma el df creado en la anterior función.

7. Función marketing: Función que recoge la lista de clientes y orquesta el resto de funciones. Muestra el df con toda la información de los clientes antes de que se ejecute la funcion mostrar respuestas.

In [ ]:
import pandas as pd

In [ ]:
lista_clientes = [
    {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
    {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
    {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
    {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
    {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
    {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
    {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
    {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
    {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
    {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
]

In [ ]:
def procesar_clientes(lista_clientes):
  """
  Función que pasa la lista de diccionarios, con la info de los clientes a un
  diccionario de diccionarios, donde la clave principal es el id_cliente y su
  valor el diccionario con el resto de información. Así mismo, la función procesa
  tres funciones más para ampliar la información del cliente.

  Argumento recibido: lista de diccionarios con la información de los clientes.
  Retorna un diccionario de diccionarios con la información de los clientes
  ampliada.
  """
  diccionario_clientes = {
    cliente["id_client"]: {k: v for k, v in cliente.items() if k != "id_client"}
    for cliente in lista_clientes
    }

  for datos_cliente in diccionario_clientes.values():

    datos_cliente.update(obtener_segmento_y_factor(datos_cliente["codi_comportament"])) #añade elementos al diccionario según el valor del código de comportamiento.
    datos_cliente["f_edad"] = obtener_factor_edad(datos_cliente["grup_edat"]) #Crea un nuevo elemento
    datos_cliente["riesgo_final"] = calcular_riesgo(datos_cliente["f_codigo"], datos_cliente["f_edad"])

  return diccionario_clientes

In [ ]:
#Prueba función:
procesar_clientes(lista_clientes)

{1: {'nom': 'Laura Serra',
  'edat': 23,
  'grup_edat': '18-25',
  'codi_comportament': 4,
  'segmento': 'Crítico',
  'mensaje': '¿Te acuerdas de estos articulos? Ahora estan a un 10% de descuento',
  'f_codigo': 0.9,
  'f_edad': 1.2,
  'riesgo_final': 1.08},
 2: {'nom': 'Marc Vidal',
  'edat': 35,
  'grup_edat': '26-40',
  'codi_comportament': 3,
  'segmento': 'Interesado con lazo',
  'mensaje': 'Tines articulos en tu carrito, aprovecha antes de que se agoten',
  'f_codigo': 0.75,
  'f_edad': 1.0,
  'riesgo_final': 0.75},
 3: {'nom': 'Ana López',
  'edat': 29,
  'grup_edat': '26-40',
  'codi_comportament': 2,
  'segmento': 'Interesado vago',
  'mensaje': 'Estás a un paso de obtener tus artículo, ¿Necesitas ayuda?',
  'f_codigo': 0.5,
  'f_edad': 1.0,
  'riesgo_final': 0.5},
 4: {'nom': 'Joan Riera',
  'edat': 19,
  'grup_edat': '18-25',
  'codi_comportament': 2,
  'segmento': 'Interesado vago',
  'mensaje': 'Estás a un paso de obtener tus artículo, ¿Necesitas ayuda?',
  'f_codigo': 0.5,
  'f_edad': 1.2,
  'riesgo_final': 0.6},
 5: {'nom': 'Mónica Pérez',
  'edat': 47,
  'grup_edat': '41-60',
  'codi_comportament': 4,
  'segmento': 'Crítico',
  'mensaje': '¿Te acuerdas de estos articulos? Ahora estan a un 10% de descuento',
  'f_codigo': 0.9,
  'f_edad': 0.85,
  'riesgo_final': 0.77},
 6: {'nom': 'Luis García',
  'edat': 52,
  'grup_edat': '41-60',
  'codi_comportament': 1,
  'segmento': 'Interes inicial',
  'mensaje': 'No te olvides de tus articulos, te están esperando',
  'f_codigo': 0.25,
  'f_edad': 0.85,
  'riesgo_final': 0.21},
 7: {'nom': 'Pilar Sánchez',
  'edat': 61,
  'grup_edat': '60+',
  'codi_comportament': 3,
  'segmento': 'Interesado con lazo',
  'mensaje': 'Tines articulos en tu carrito, aprovecha antes de que se agoten',
  'f_codigo': 0.75,
  'f_edad': 0.7,
  'riesgo_final': 0.52},
 8: {'nom': 'Eva Martín',
  'edat': 38,
  'grup_edat': '26-40',
  'codi_comportament': 0,
  'segmento': 'Bajo interes',
  'mensaje': 'Mira nuestros BestSellers',
  'f_codigo': 0.1,
  'f_edad': 1.0,
  'riesgo_final': 0.1},
 9: {'nom': 'Diego Romero',
  'edat': 24,
  'grup_edat': '18-25',
  'codi_comportament': 1,
  'segmento': 'Interes inicial',
  'mensaje': 'No te olvides de tus articulos, te están esperando',
  'f_codigo': 0.25,
  'f_edad': 1.2,
  'riesgo_final': 0.3},
 10: {'nom': 'Núria Costa',
  'edat': 33,
  'grup_edat': '26-40',
  'codi_comportament': 4,
  'segmento': 'Crítico',
  'mensaje': '¿Te acuerdas de estos articulos? Ahora estan a un 10% de descuento',
  'f_codigo': 0.9,
  'f_edad': 1.0,
  'riesgo_final': 0.9}}

In [ ]:
def obtener_segmento_y_factor(valor_int):
  """
  Función que devuelve el diccionario con los datos de segmento,
  mensaje publicitario y factor comportamiento correctamente asignado
  según el codigo_comportamiento.

  Argumento recibido: valor de la clave codi_comportament.
  Retorna un diccionario.
  """
  dic_comportamiento = {
      0:{"segmento": "Bajo interes", "mensaje" : "Mira nuestros BestSellers", "f_codigo" : 0.10},
      1: {"segmento": "Interes inicial", "mensaje" : "No te olvides de tus articulos, te están esperando", "f_codigo" : 0.25},
      2: {"segmento": "Interesado vago", "mensaje" : "Estás a un paso de obtener tus artículo, ¿Necesitas ayuda?", "f_codigo" : 0.50},
      3: {"segmento": "Interesado con lazo", "mensaje" : "Tines articulos en tu carrito, aprovecha antes de que se agoten", "f_codigo" : 0.75},
      4: {"segmento": "Crítico", "mensaje" : "¿Te acuerdas de estos articulos? Ahora estan a un 10% de descuento", "f_codigo" : 0.90}
      }

  return dic_comportamiento[valor_int]

In [ ]:
def obtener_factor_edad(valor_str):
  """
  Función que devuelve el valor de los datos de factor edad,
  correctamente asignado según el grup_edat.

  Argumento recibido: valor de la clave grup_edat.
  Retorna valor.
  """
  dic_edad = {
      "18-25": 1.20,
      "26-40": 1.00,
      "41-60": 0.85,
      "60+": 0.70
      }

  return dic_edad[valor_str]

In [ ]:
def calcular_riesgo(valor_codigo, valor_edad):
  """
  Funcion que devuelve el diccionario con el factor riesgo calculado
  f_codigo * f_edad

  Argumento recibido: valor de la clave f_codigo y f_edad.
  Retorna valor.
  """
  calculo = round(valor_codigo * valor_edad, 2)

  return calculo

In [ ]:
def mostrar_df(diccionario_clientes):
  """
  Función que genera un DF apartir del diccionario anidado final.

  Argumento recibido: Diccionario de diccionario.
  Retorna un dataframe
  """
  df = pd.DataFrame(
      diccionario_clientes
      ).T.reset_index().rename(
          columns={
              "index": "id_cliente", #establece el indice del df como el valor del id de cliente
              "nom": "nombre",
              "edat": "edad",
              "grup_edat": "grupo_edad",
              "codi_comportament":"codigo_comportamiento"
              } #se cambian los nombres de las columnas a castellano
          )
  return df

In [ ]:
#Prueba función
dic_prueba = {1: {'nom': 'Laura Serra',
  'edat': 23,
  'grup_edat': '18-25',
  'codi_comportament': 4,
  'segmento': 'Crítico',
  'mensaje': '¿Te acuerdas de estos articulos? Ahora estan a un 10% de descuento',
  'f_codigo': 0.9,
  'f_edad': 1.2,
  'riesgo_final': 1.08},
 2: {'nom': 'Marc Vidal',
  'edat': 35,
  'grup_edat': '26-40',
  'codi_comportament': 3,
  'segmento': 'Interesado con lazo',
  'mensaje': 'Tines articulos en tu carrito, aprovecha antes de que se agoten',
  'f_codigo': 0.75,
  'f_edad': 1.0,
  'riesgo_final': 0.75},
 3: {'nom': 'Ana López',
  'edat': 29,
  'grup_edat': '26-40',
  'codi_comportament': 2,
  'segmento': 'Interesado vago',
  'mensaje': 'Estás a un paso de obtener tus artículo, ¿Necesitas ayuda?',
  'f_codigo': 0.5,
  'f_edad': 1.0,
  'riesgo_final': 0.5},
 4: {'nom': 'Joan Riera',
  'edat': 19,
  'grup_edat': '18-25',
  'codi_comportament': 2,
  'segmento': 'Interesado vago',
  'mensaje': 'Estás a un paso de obtener tus artículo, ¿Necesitas ayuda?',
  'f_codigo': 0.5,
  'f_edad': 1.2,
  'riesgo_final': 0.6},
 5: {'nom': 'Mónica Pérez',
  'edat': 47,
  'grup_edat': '41-60',
  'codi_comportament': 4,
  'segmento': 'Crítico',
  'mensaje': '¿Te acuerdas de estos articulos? Ahora estan a un 10% de descuento',
  'f_codigo': 0.9,
  'f_edad': 0.85,
  'riesgo_final': 0.77},
 6: {'nom': 'Luis García',
  'edat': 52,
  'grup_edat': '41-60',
  'codi_comportament': 1,
  'segmento': 'Interes inicial',
  'mensaje': 'No te olvides de tus articulos, te están esperando',
  'f_codigo': 0.25,
  'f_edad': 0.85,
  'riesgo_final': 0.21},
 7: {'nom': 'Pilar Sánchez',
  'edat': 61,
  'grup_edat': '60+',
  'codi_comportament': 3,
  'segmento': 'Interesado con lazo',
  'mensaje': 'Tines articulos en tu carrito, aprovecha antes de que se agoten',
  'f_codigo': 0.75,
  'f_edad': 0.7,
  'riesgo_final': 0.52},
 8: {'nom': 'Eva Martín',
  'edat': 38,
  'grup_edat': '26-40',
  'codi_comportament': 0,
  'segmento': 'Bajo interes',
  'mensaje': 'Mira nuestros BestSellers',
  'f_codigo': 0.1,
  'f_edad': 1.0,
  'riesgo_final': 0.1},
 9: {'nom': 'Diego Romero',
  'edat': 24,
  'grup_edat': '18-25',
  'codi_comportament': 1,
  'segmento': 'Interes inicial',
  'mensaje': 'No te olvides de tus articulos, te están esperando',
  'f_codigo': 0.25,
  'f_edad': 1.2,
  'riesgo_final': 0.3},
 10: {'nom': 'Núria Costa',
  'edat': 33,
  'grup_edat': '26-40',
  'codi_comportament': 4,
  'segmento': 'Crítico',
  'mensaje': '¿Te acuerdas de estos articulos? Ahora estan a un 10% de descuento',
  'f_codigo': 0.9,
  'f_edad': 1.0,
  'riesgo_final': 0.9}}

mostrar_df(dic_prueba)

,id_cliente,nombre,edad,grupo_edad,codigo_comportamiento,segmento,mensaje,f_codigo,f_edad,riesgo_final
0,1,Laura Serra,23,18-25,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,1.2,1.08
1,2,Marc Vidal,35,26-40,3,Interesado con lazo,"Tines articulos en tu carrito, aprovecha antes...",0.75,1.0,0.75
2,3,Ana López,29,26-40,2,Interesado vago,"Estás a un paso de obtener tus artículo, ¿Nece...",0.5,1.0,0.5
3,4,Joan Riera,19,18-25,2,Interesado vago,"Estás a un paso de obtener tus artículo, ¿Nece...",0.5,1.2,0.6
4,5,Mónica Pérez,47,41-60,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,0.85,0.77
5,6,Luis García,52,41-60,1,Interes inicial,"No te olvides de tus articulos, te están esper...",0.25,0.85,0.21
6,7,Pilar Sánchez,61,60+,3,Interesado con lazo,"Tines articulos en tu carrito, aprovecha antes...",0.75,0.7,0.52
7,8,Eva Martín,38,26-40,0,Bajo interes,Mira nuestros BestSellers,0.1,1.0,0.1
8,9,Diego Romero,24,18-25,1,Interes inicial,"No te olvides de tus articulos, te están esper...",0.25,1.2,0.3
9,10,Núria Costa,33,26-40,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,1.0,0.9

In [ ]:
def mostrar_respuestas(df_clientes):
  """
  Función que resuelve las preguntas del departamento de mkt:
  1. Quins clients s'han de contactar primer en una campanya de retargeting?
  2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?
  (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?).
  3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
  4. Quin client seria el més rendible de recuperar?

  Argumento recibido: DataFrame de clientes
  No retorna nada, muestra en pantalla (imprime) tanto las preguntas como el resultado.
  """

  print("\n"+"-"*30)
  print("\n 1. Quins clients s'han de contactar primer en una campanya de retargeting?\n")

#Ordena el df por riesgo final y si empate codigo comportamiento y muestra aquellos
#clientes con un riesgo final igual o superior a 0.5.
  df_pregunta_1 = df_clientes[
      df_clientes["riesgo_final"] >= 0.5].sort_values(by=[
          "riesgo_final",
          "codigo_comportamiento"
          ], ascending = [False, False])
  display(df_pregunta_1)
  print("\n Los clientes que se deberian contactar primero son aquellos con un riesgo final elevado, superior a 0.5.\n")


#Ordena los clientes por codigo de comportamiento y dentro de ese orden por
#por grupo de edad. Mostrando una serie de columnas.
  print("\n"+"-"*30)
  print("\n 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?\n")
  df_pregunta_2 = df_clientes.sort_values(
      by=["codigo_comportamiento", "grupo_edad"],
      ascending = [False, True])
  display(df_pregunta_2[["nombre",
                        "grupo_edad",
                        "codigo_comportamiento",
                        "f_codigo",
                        "f_edad",
                        "riesgo_final"
                        ]])
  print("\n Dentro de un mismo grupo de codigo de comportamiento"
  "el factor edad varia el riesgo final."
  " Ha menor edad mayor es el riesgo y a mayor edad menor es el riesgo.")


#Muestra la informacion de los clientes que tienen un riesgo final inferior a 0.3.
  print("\n"+"-"*30)
  print("\n 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?\n")
  df_pregunta_3 = df_clientes[df_clientes["riesgo_final"] < 0.3]
  display(df_pregunta_3[["id_cliente",
                        "nombre",
                        "edad",
                        "codigo_comportamiento"
                        ]])
  print("\n Los clientes con riesgo final inferior al 0.3 son poco intersantes de recuperar,"
  " ya sean por el comportamiento presentado o por la franja de edad en la que se situan.")


#Calcula el máximo riesgo final y muestra al cliente o clientes que tengan dicho riesgo.
  print("\n"+"-"*30)
  print("\n 4. Quin client seria el més rendible de recuperar?")
  max_df = df_clientes["riesgo_final"].max()
  df_pregunta_4a = df_clientes[df_clientes["riesgo_final"] == max_df]
  display(df_pregunta_4a[["id_cliente",
                        "nombre",
                        "grupo_edad",
                        "codigo_comportamiento",
                        "f_codigo",
                        "f_edad",
                        "riesgo_final"
                        ]])
  print("\n Se deberia contactar primero a todos los clientes o cliente que tengan el valor de riesgo mas alto.\n\n"
  "Sin embargo, los clientes comprendidos en la siguiente categoria de grupo de edad tambien son muy interesante de contactar")

  #muestra la información de aquellos clientes que su código de comportamiento sea igual a 3
  #y que su grupo de edad este en 26-40 o 18-25.
  df_pregunta_4b = df_clientes[(df_clientes["codigo_comportamiento"] == 3) & (df_clientes["grupo_edad"].isin(["26-40","18-25"]))]
  display(df_pregunta_4b[["id_cliente",
                        "nombre",
                        "grupo_edad",
                        "codigo_comportamiento",
                        "f_codigo",
                        "f_edad",
                        "riesgo_final"
                        ]])
  print("\n Ya que son los clientes que han abandonado recientemente la compra y tienen una franja de edad con una puntuacion elevada."
  " Permitiendo accedes a ellos con mayor facilidad")

In [ ]:
def funcion_mkt(lista_facilitada):
  """
  Función general que gestiona el análisi de la recuperacion de carritos abandonados.

  Argumento recibido: Lista de diccionarios con la información de los clientes.
  No retorna nada, muestra en pantalla df de los clientes y las respuestas a las
  preguntas.
  """
  dic_clientes = procesar_clientes(lista_facilitada)
  df_cliente = mostrar_df(dic_clientes)
  print("\n --- DataFrame clientes en la campaña de Retargeting---\n")
  display(df_cliente)
  mostrar_respuestas(df_cliente)

In [ ]:
funcion_mkt(lista_clientes)

 --- DataFrame clientes en la campaña de Retargeting---

,id_cliente,nombre,edad,grupo_edad,codigo_comportamiento,segmento,mensaje,f_codigo,f_edad,riesgo_final
0,1,Laura Serra,23,18-25,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,1.2,1.08
1,2,Marc Vidal,35,26-40,3,Interesado con lazo,"Tines articulos en tu carrito, aprovecha antes...",0.75,1.0,0.75
2,3,Ana López,29,26-40,2,Interesado vago,"Estás a un paso de obtener tus artículo, ¿Nece...",0.5,1.0,0.5
3,4,Joan Riera,19,18-25,2,Interesado vago,"Estás a un paso de obtener tus artículo, ¿Nece...",0.5,1.2,0.6
4,5,Mónica Pérez,47,41-60,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,0.85,0.77
5,6,Luis García,52,41-60,1,Interes inicial,"No te olvides de tus articulos, te están esper...",0.25,0.85,0.21
6,7,Pilar Sánchez,61,60+,3,Interesado con lazo,"Tines articulos en tu carrito, aprovecha antes...",0.75,0.7,0.52
7,8,Eva Martín,38,26-40,0,Bajo interes,Mira nuestros BestSellers,0.1,1.0,0.1
8,9,Diego Romero,24,18-25,1,Interes inicial,"No te olvides de tus articulos, te están esper...",0.25,1.2,0.3
9,10,Núria Costa,33,26-40,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,1.0,0.9

------------------------------

 1. Quins clients s'han de contactar primer en una campanya de retargeting?

,id_cliente,nombre,edad,grupo_edad,codigo_comportamiento,segmento,mensaje,f_codigo,f_edad,riesgo_final
0,1,Laura Serra,23,18-25,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,1.2,1.08
9,10,Núria Costa,33,26-40,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,1.0,0.9
4,5,Mónica Pérez,47,41-60,4,Crítico,¿Te acuerdas de estos articulos? Ahora estan a...,0.9,0.85,0.77
1,2,Marc Vidal,35,26-40,3,Interesado con lazo,"Tines articulos en tu carrito, aprovecha antes...",0.75,1.0,0.75
3,4,Joan Riera,19,18-25,2,Interesado vago,"Estás a un paso de obtener tus artículo, ¿Nece...",0.5,1.2,0.6
6,7,Pilar Sánchez,61,60+,3,Interesado con lazo,"Tines articulos en tu carrito, aprovecha antes...",0.75,0.7,0.52
2,3,Ana López,29,26-40,2,Interesado vago,"Estás a un paso de obtener tus artículo, ¿Nece...",0.5,1.0,0.5

 Los clientes que se deberian contactar primero son aquellos con un riesgo final elevado, superior a 0.5.


------------------------------

 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?

          nombre grupo_edad codigo_comportamiento f_codigo f_edad riesgo_final
0    Laura Serra      18-25                     4      0.9    1.2         1.08
9    Núria Costa      26-40                     4      0.9    1.0          0.9
4   Mónica Pérez      41-60                     4      0.9   0.85         0.77
1     Marc Vidal      26-40                     3     0.75    1.0         0.75
6  Pilar Sánchez        60+                     3     0.75    0.7         0.52
3     Joan Riera      18-25                     2      0.5    1.2          0.6
2      Ana López      26-40                     2      0.5    1.0          0.5
8   Diego Romero      18-25                     1     0.25    1.2          0.3
5    Luis García      41-60                     1     0.25   0.85         0.21
7     Eva Martín      26-40                     0      0.1    1.0          0.1

 Dentro de un mismo grupo de codigo de comportamientoel factor edad varia el riesgo final. Ha menor edad mayor es el riesgo y a mayor edad menor es el riesgo.

------------------------------

 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?

   id_cliente       nombre edad codigo_comportamiento
5           6  Luis García   52                     1
7           8   Eva Martín   38                     0

 Los clientes con riesgo final inferior al 0.3 son poco intersantes de recuperar, ya sean por el comportamiento presentado o por la franja de edad en la que se situan.

------------------------------

 4. Quin client seria el més rendible de recuperar?

,id_cliente,nombre,grupo_edad,codigo_comportamiento,f_codigo,f_edad,riesgo_final
0,1,Laura Serra,18-25,4,0.9,1.2,1.08

 Se deberia contactar primero a todos los clientes o cliente que tengan el valor de riesgo mas alto.

Sin embargo, los clientes comprendidos en la siguiente categoria de grupo de edad tambien son muy interesante de contactar

,id_cliente,nombre,grupo_edad,codigo_comportamiento,f_codigo,f_edad,riesgo_final
1,2,Marc Vidal,26-40,3,0.75,1.0,0.75

 Ya que son los clientes que han abandonado recientemente la compra y tienen una franja de edad con una puntuacion elevada. Permitiendo accedes a ellos con mayor facilidad

## NIVEL 2

### **EJERCICIO 1**

**Gestió de risc i priorització de pacients**

Treballes com a analista de dades en un centre mèdic especialitzat. Diversos pacients han enviat els seus símptomes a través d'un formulari online, però les dades arriben en un format desordenat i poc estructurat, i l'equip mèdic necessita que els organitzis per poder prioritzar l'ordre d'atenció segons la gravetat.

A continuació tens una llista amb informació real procedent del sistema:
  
  lista_pacientes

El departament mèdic també t'ha proporcionat el següent diccionari de nivells de risc per símptoma:

  nivel_riesgo

 Objectius
L'objectiu és transformar aquestes dades en informació útil per als metges. A partir dels registres en brut, has de:

- Convertir cada string en una estructura neta (diccionari o similar).
- Separar i normalitzar la llista de símptomes:
minúscules
eliminar espais
dividir correctament per comes
- Assignar un risc a cada símptoma utilitzant el diccionari nivells_risc.

- Calcular el risc total de cada pacient sumant els valors.

- Ordenar els pacients de major a menor risc per determinar la prioritat d'atenció.

Important:

En aquest Nivell 2 ja no et proporcionem la llista de funcions que has de crear. Ets tu qui ha de plantejar quines funcions necessites i com modularitzar el procés.

Tot i així, es recomana que:

- La funció principal orquestri tots els passos.

- Cada subfunció faci una sola tasca concreta (neteja, conversió, càlcul, ordenació...).
- La lògica estigui separada de manera neta i coherent.

Resultat esperat:
Un DataFrame o un diccionari amb:

  - nom
  - edat
  - símptomes normalitzats
  - risc_total
  
I un apartat final amb els pacients ordenats per prioritat (més risc → primer).

**ESTRUCTURA ALGORITMO**

La función principal (gestion_pacientes_urgencia ) procesara el listado con la información de los pacientes y sus sintomas, otorgando una puntuación según sintoma establecido por el hospital y retorna un dataframe con los pacientes ordenados de mayor a menor riesgo.

Las subfunciones son las siguientes:
1. Función convertir_lista_dic: Función que tomas los datos de la lista facilitada y la convierte en una lista de diccionarios, donde la información de cada paciente esta en un diccionario. Para ello, se separan los datos facilitados y se une con la lista de claves.
El valor de la clave sintomas queda como una lista de sintomas en bruto
Retorna lista de diccionarios.
2. Función normalizacion de sintomas: En esta función se convierte los valores de los sintomas en una lista, limpiando los datos para que se puedan procesas.
3. Función asignación riesgo: Añade la suma de las puntuaciones según los sintomas que presenta el paciente.
4. Función obtener df pacientes: Función que convierte la lista de diccionarios en un DataFrame y lo ordena según el valor del riesgo. Lo retorna y es en la función principal donde se imprime en pantalla.

In [ ]:
import pandas as pd

In [ ]:
lista_pacientes = [
    "Maria|45|tos, Fiebre Alta, dolor_pecho",
    "Luis|33|dolor_cabeza,faTiga",
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
    "Jordi|52|fatiga , tos",
    "Anna |29|fiebre alta, dolor_cabeza"]

In [ ]:
def convertir_lista_dic(lista_pacientes):
  """
  Función que tomas los datos de la lista facilitada y la convierte
  en una lista de diccionarios, donde la información de cada paciente
  esta en un diccionario.

  Arguemto reibido: Lista de pacientes
  Retorna una lista de diccionarios
  """
  lista_separada = []
  lista_claves = ["nombre", "edad", "sintomas"]
  for paciente in lista_pacientes:
    paciente_separado = paciente.split("|") #separa la informacion de cada elemento de la lista por donde hay |
    lista_separada.append(paciente_separado) #añade cada elemento a una nueva lista

  lista_dic_pacientes = []
  for paciente in lista_separada:
    diccionario_paciente = dict(zip(lista_claves, paciente)) #crea diccionario en cada elemento de la lista
    lista_dic_pacientes.append(diccionario_paciente)#convirtiendose en una lista de

  return lista_dic_pacientes

In [ ]:
#Prueba función:
l_dic_prueba = convertir_lista_dic(lista_pacientes)

In [ ]:
def normalizacion_sintomas(lista_dic_pacientes):
  """
  Función que normaliza los valores de los sintomas
  todo en minusculas, separando cada sintoma por donde esta la ",",
  limpiando los espacios en blanco al inicio y final y uniendo las palabras con _.

  Argumento recibido: lista de diccionarios
  Retorna lista de diccionarios
  """
  for paciente in lista_dic_pacientes:
    paciente["sintomas"] = paciente["sintomas"].lower() # paso a minusculas los sintomas
    paciente["sintomas"] = paciente["sintomas"].split(",") # separa los distintos sintomas por donde esta la coma
    paciente["sintomas"] = [sintoma.strip() for sintoma in paciente["sintomas"]] #limpieza espacios en blanco
    paciente["sintomas"] = [sintoma.replace(" ", "_") for sintoma in paciente["sintomas"]] #cambio espcaio en blanco intermedio por "_".

  return lista_dic_pacientes

In [ ]:
#Prueba función:
a = normalizacion_sintomas(l_dic_prueba)

In [ ]:
def asignacion_riesgo(lista_pacientes):
  """
  Función que calcula el riego del paciente, en función de los sintomas
  presentados y lo añade a la clave "riesgo" al diccionario según las
  puntuaciones por sintoma facilitadas por el hospital.

  Argumento recibido: Lista diccionario
  Restorna la misma lista de diccionarios, con los diccionarios ampliados
  """
  dic_nivel_riesgo = {
    "fiebre_alta": 3,
    "dificultad_respirar": 5,
    "dolor_pecho": 4,
    "tos": 1,
    "fatiga": 1,
    "dolor_cabeza": 1
} #Se deja el diccionario como variable local de la función para que no se vaya
#arrastrando desde el inicio y de necesitar cambiar valores solo cambiarlos aqui.

  for paciente in lista_pacientes:
    sintomas = paciente["sintomas"] #bucle para iterar hasta los sintomas
    suma_sintomas = 0
    for sintoma in sintomas: #bucle para iterar dentro de la lista de sintomas
      if sintoma in dic_nivel_riesgo:
        suma_sintomas += dic_nivel_riesgo[sintoma]
    paciente["riesgo"] = suma_sintomas

  return lista_pacientes

In [ ]:
#Prueba función:
asignacion_riesgo(a)

[{'nombre': 'Maria',
  'edad': '45',
  'sintomas': ['tos', 'fiebre_alta', 'dolor_pecho'],
  'riesgo': 8},
 {'nombre': 'Luis',
  'edad': '33',
  'sintomas': ['dolor_cabeza', 'fatiga'],
  'riesgo': 2},
 {'nombre': 'Sara',
  'edad': '67',
  'sintomas': ['fiebre_alta', 'dificultad_respirar', 'tos'],
  'riesgo': 9},
 {'nombre': 'Jordi', 'edad': '52', 'sintomas': ['fatiga', 'tos'], 'riesgo': 2},
 {'nombre': 'Anna ',
  'edad': '29',
  'sintomas': ['fiebre_alta', 'dolor_cabeza'],
  'riesgo': 4}]

In [ ]:
def obtener_df_pacientes(lista_diccionario_con_riesgo):
  """
  Pasa el diccionario final a un df
  y se devuelve ya ordenado de mayor a menor riesgo.

  Argumento recibido: Lista de diccionarios
  Retorna un DataFrame
  """

  #Conversión de la lista de diccionarios en df:
  df_hospital = pd.DataFrame(lista_diccionario_con_riesgo)
  #Ordena el df según la columna de riesgo de mayor a menor:
  df_hosp_ordenado = df_hospital.sort_values(by = ["riesgo"], ascending = False)
  #Inicia lo el indice en 1 y termina en la longitud del df+1:
  df_hosp_ordenado.index = pd.RangeIndex(start = 1, stop = len(df_hospital) + 1)
  #En cada linea del df, en la columna sintomas pasa convierte en string cada elemento y los une mediante una ",":
  df_hosp_ordenado["sintomas"] = [', '.join(map(str, x)) for x in df_hosp_ordenado["sintomas"]]


  return df_hosp_ordenado

In [ ]:
def gestion_pacientes_urgencia (lista):
  """
  Función que ejecuta y organiza la atención de los pacientes
  según la lista facilitada de pacientes.

  Argumento recibido: Lista con la información de clientes.
  Retorna el df ordenado
  """
  lista_diccionario_pacientes = convertir_lista_dic(lista)
  lista_dic_pacientes_sintomas_normalizados = normalizacion_sintomas(lista_diccionario_pacientes)
  lista_final = asignacion_riesgo(lista_dic_pacientes_sintomas_normalizados)

  return obtener_df_pacientes(lista_final)

In [ ]:
gestion_pacientes_urgencia(lista_pacientes)

  nombre edad                               sintomas  riesgo
1   Sara   67  fiebre_alta, dificultad_respirar, tos       9
2  Maria   45          tos, fiebre_alta, dolor_pecho       8
3  Anna    29              fiebre_alta, dolor_cabeza       4
4   Luis   33                   dolor_cabeza, fatiga       2
5  Jordi   52                            fatiga, tos       2

### **Ejercicio 2**

**Classificació de clients de segurs**

Treballes com a analista de dades en una companyia asseguradora.
L'empresa vol calcular el risc dels clients, el preu estimat de la pòlissa i la probabilitat de frau, utilitzant un codi de comportament que ha estat generat per un model intern.

Tens la següent llista de clients:
I aquest diccionari amb les categories del sistema:

El preu final s'ha de calcular amb la fórmula:

preu_final = preu_base * (1 + edat/100)

 Objectius
  - Classificar cada client utilitzant nivells_seguro (sense if/elif).
  - Afegir:
      - La categoria
      - El preu base
      - La probabilitat de frau
  - Calcular el preu final de la pòlissa amb la fórmula donada.

  - Crear un DataFrame o diccionari amb la informació final.

- Ordenar els clients:
    - Per probabilitat de frau (descendent).
    - Per preu final.

 Important

Igual que a l'Exercici 1, en aquest nivell ets tu qui ha de definir les funcions necessàries. Es recomana mantenir el codi modular, on:

  - Cada funció resol un pas del procés.
  - La funció principal delega totes les tasques.

Resultat esperat:

Un DataFrame o un diccionari amb:
- Nom
- Edat
- Categoria
- Preu_base
- Preu_final
- Probabilitat_frau
- Un apartat d'anàlisi on s'indiqui:
- Quin client té més probabilitat de frau
- Quin té el preu final més alt
- Qui seria prioritari de revisar manualment

**ESTRUCUTRA ALGORITMO**

La función principal (calculo_precios_seguros) unifica una serie de funciones con tal de conseguir ampliar la información de los clientes (info guardad en lista de diccionarios) con la información de riesgo de fraude (info en diccionario de diccionarios), calcular precio seguro final y guardar esta información en un DataFrame y resolver preguntas realizadas por el departamento.

Subfunciones:
1.   Función unir info clientes seguro: Amplia la informacion de cada cliente con la información que le pertoca de nivel de fraude según sel valor del codigo establecido en los datos del cliente.
2.   Función calculo precio final: Calcula el precio final de la poliza según los datos del cliente.
3. Función creación resultado df: Crea un dataframe segun los datos obtenidos. Renombra el nombre de las columnas y ordena los clientes según el valor del fraude de mayor a menor y según el precio final de menor a mayor.
4. Función análisi datos: Funcion que recoge las preguntas, calcula las preguntas sobre el DataFrame y muestra las respuestas.

In [ ]:
import pandas as pd
import copy

In [ ]:
clients = [
    {"nom": "Ana", "edat": 42, "codi": 0},
    {"nom": "Carlos", "edat": 30, "codi": 2},
    {"nom": "Isabel", "edat": 55, "codi": 3},
    {"nom": "Jorge", "edat": 40, "codi": 1},
    {"nom": "Marta", "edat": 28, "codi": 0}
]

nivells_seguro = {
    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},
    3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30}
}

In [ ]:
def unir_info_clientes_seguro(lista_diccionarios, diccionario_diccionarios):
  """
  Amplia la informacion de cada cliente con la información que le pertoca
  de nivel de fraude según sel valor del codigo establecido en los datos del cliente.

  Argumento recibidos:
    1. Lista de diccionarios con información de clientes.
    2. Diccionario de diccionarios con la información de las categorias riesgos.
  Retorna la lista de diccionarios con la info de los clientes ampliada y los valores borrados.
  """
  #Hago deep copies para que se guarden los datos de los diccionarios anidados
  lista_clientes = copy.deepcopy(lista_diccionarios)
  dic_niveles = copy.deepcopy(diccionario_diccionarios)
  valores_borrados = {}
  for cliente in lista_clientes:
    valor_codigo = cliente["codi"]#Para saber que valor tiene el codigo con el que hay que ampliar la información de cliente
    cliente.update(dic_niveles[valor_codigo]) #Amplia el diccionario de cada cliente con los elementos que tiene el diccionario de niveles
    valores_borrados[cliente["nom"]] = cliente.pop("codi")#Por tal de no tener valores redundantes, elimino el elemento del codigo de cada cliente
    #y por si acaso los guardo junto con el nombre del cliente (k:v)

  return lista_clientes, valores_borrados

In [ ]:
#Prueba función:
ld_a = unir_info_clientes_seguro(clients, nivells_seguro)

([{'nom': 'Ana',
   'edat': 42,
   'categoria': 'Baix risc',
   'preu_base': 120,
   'fraude': 0.01},
  {'nom': 'Carlos',
   'edat': 30,
   'categoria': 'Risc alt',
   'preu_base': 350,
   'fraude': 0.15},
  {'nom': 'Isabel',
   'edat': 55,
   'categoria': 'Risc crític',
   'preu_base': 500,
   'fraude': 0.3},
  {'nom': 'Jorge',
   'edat': 40,
   'categoria': 'Risc mitjà',
   'preu_base': 200,
   'fraude': 0.05},
  {'nom': 'Marta',
   'edat': 28,
   'categoria': 'Baix risc',
   'preu_base': 120,
   'fraude': 0.01}],
 {'Ana': 0, 'Carlos': 2, 'Isabel': 3, 'Jorge': 1, 'Marta': 0})

In [ ]:
def calculo_precio_final(lista_clientes):
  """
  Calcula el precio final de la poliza según los datos del cliente.

  Argumento recibido: lista de diccionarios con la info de clientes.
  Retorna la misma lista con nuevo elemento "precio_final".
  """
  for cliente in lista_clientes:
    cliente["precio_final"] = round(cliente["preu_base"]*( 1 + cliente["edat"] / 100), 2)

  return lista_clientes

In [ ]:
#Prueba función:
ld_b = calculo_precio_final(ld_a)

[{'nom': 'Ana',
  'edat': 42,
  'categoria': 'Baix risc',
  'preu_base': 120,
  'fraude': 0.01,
  'precio_final': 170.4},
 {'nom': 'Carlos',
  'edat': 30,
  'categoria': 'Risc alt',
  'preu_base': 350,
  'fraude': 0.15,
  'precio_final': 455.0},
 {'nom': 'Isabel',
  'edat': 55,
  'categoria': 'Risc crític',
  'preu_base': 500,
  'fraude': 0.3,
  'precio_final': 775.0},
 {'nom': 'Jorge',
  'edat': 40,
  'categoria': 'Risc mitjà',
  'preu_base': 200,
  'fraude': 0.05,
  'precio_final': 280.0},
 {'nom': 'Marta',
  'edat': 28,
  'categoria': 'Baix risc',
  'preu_base': 120,
  'fraude': 0.01,
  'precio_final': 153.6}]

In [ ]:
def creacion_resultados_df (lista_diccionarios):
  """
  Crea un dataframe segun los datos obtenidos.
  Renombra el nombre de las columnas y ordena los clientes según el valor del
  fraude de mayor a menor y según el precio final de menor a mayor.

  Argumento recibido: Lista de diccionarios con datos de cliente.
  Retorna DataFrame y lo muestra en pantalla.
  """
  df_seguro = pd.DataFrame(lista_diccionarios).rename(columns= {
    "nom":"nombre",
    "edat":"edad",
    "categoria": "Categoria",
    "preu_base": "precio_base",
    "fraude": "fraude",
    "precio_final": "precio_final"
    }).sort_values(by = ["fraude",
                     "precio_final"], ascending = [False, True])#Se actualiza el indice.

  df_seguro.index = range(1, len(df_seguro) + 1)#Se actualiza el indice, iniciando en valor 1.
  display(df_seguro)
  return df_seguro

In [ ]:
#Prueba función:
creacion_resultados_df(ld_b)

   nombre  edad    Categoria  precio_base  fraude  precio_final
1  Isabel    55  Risc crític          500    0.30         775.0
2  Carlos    30     Risc alt          350    0.15         455.0
3   Jorge    40   Risc mitjà          200    0.05         280.0
4   Marta    28    Baix risc          120    0.01         153.6
5     Ana    42    Baix risc          120    0.01         170.4

   nombre  edad    Categoria  precio_base  fraude  precio_final
1  Isabel    55  Risc crític          500    0.30         775.0
2  Carlos    30     Risc alt          350    0.15         455.0
3   Jorge    40   Risc mitjà          200    0.05         280.0
4   Marta    28    Baix risc          120    0.01         153.6
5     Ana    42    Baix risc          120    0.01         170.4

In [ ]:
def analisis_datos(df_seguro):
  """
  Funcion que recoge las preguntas, calcula las preguntas sobre el DataFrame
  y muestra las respuestas.

  Argumento recibido: Dataframe
  No retorna nada, muestra en pantalla
  """

  #Se buca el valor máximo de la columna de fraude
  #y se muestra la información del cliente o clientes cuyo valor de fraude sea
  #igual al máximo.
  print("\n\n1.Que cliente tiene más probabilidades de fraude?")
  valor_fraude_max = df_seguro["fraude"].max()
  df_pregunta_1 = df_seguro[df_seguro["fraude"] == valor_fraude_max]
  print("\nLos datos del cliente o clientes con mayor probabilidad de fraude son:\n")
  display(df_pregunta_1)

  #Se buca el valor máximo de la columna de precio final
  #y se muestra la información del cliente o clientes cuyo valor de precio final
  #sea igual al máximo.
  print("\n\n2.Quien tiene el precio final más elevado?")
  valor_precio_final_max = df_seguro["precio_final"].max()
  df_pregunta_2 = df_seguro[df_seguro["precio_final"] == valor_precio_final_max]
  print("\nLos datos del cliente o clientes con mayor precio final son:\n")
  display(df_pregunta_2)

  #Se calcula nuevo campo "puntuacion_riesgo"
  #Se buca el valor máximo de la columna puntuacion riesgo
  #y se muestra la información del cliente o clientes cuyo valor de precio final
  #sea igual al máximo.
  print("\n\n3.Quien seria prioritario de revisar manualmente?")
  df = df_seguro.copy()
  df["puntuacion_riesgo"] = df["fraude"] * df["precio_final"]
  valor_riesgo_max = df["puntuacion_riesgo"].max()
  df_pregunta_3 = df[df["puntuacion_riesgo"] == valor_riesgo_max]
  print("\nLos datos del cliente o clientes que debaria ser reivisado manualmente:\n")
  display(df_pregunta_3)

In [ ]:
def calculo_precios_seguro(lista, diccionario):
  """
  Función general que orquesta todas las funciones.

  Argumento recibidos:
  1. Lista de diccionarios con información de clientes.
  2. Diccionario de diccionarios con la información de las categorias riesgos.
  No retorna nada, se muestran los resultados de la función análisis datos.
  """
  info_unida, valores_codigo_borrados = unir_info_clientes_seguro(lista, diccionario)
  info_completa = calculo_precio_final(info_unida)
  df_final = creacion_resultados_df(info_completa)
  analisis_datos(df_final)

In [ ]:
calculo_precios_seguro(clients, nivells_seguro)

   nombre  edad    Categoria  precio_base  fraude  precio_final
1  Isabel    55  Risc crític          500    0.30         775.0
2  Carlos    30     Risc alt          350    0.15         455.0
3   Jorge    40   Risc mitjà          200    0.05         280.0
4   Marta    28    Baix risc          120    0.01         153.6
5     Ana    42    Baix risc          120    0.01         170.4

1.Que cliente tiene más probabilidades de fraude?

Los datos del cliente o clientes con mayor probabilidad de fraude son:

   nombre  edad    Categoria  precio_base  fraude  precio_final
1  Isabel    55  Risc crític          500     0.3         775.0

2.Quien tiene el precio final más elevado?

Los datos del cliente o clientes con mayor precio final son:

   nombre  edad    Categoria  precio_base  fraude  precio_final
1  Isabel    55  Risc crític          500     0.3         775.0

3.Quien seria prioritario de revisar manualmente?

Los datos del cliente o clientes que debaria ser reivisado manualmente:

,nombre,edad,Categoria,precio_base,fraude,precio_final,puntuacion_riesgo
1,Isabel,55,Risc crític,500,0.3,775.0,232.5

## Nivel 3

### **Ejercicio 1**

**Generador de contrasenyes segures**

Ets analista de dades dins el departament de Ciberseguretat d'una empresa tecnològica. S'ha detectat que la majoria de treballadors continuen utilitzant contrasenyes molt dèbils com “Asdf1234”, dates d'aniversari o combinacions fàcils d'endevinar. Per aquest motiu, el responsable del departament t'ha demanat desenvolupar un generador de contrasenyes segures, totalment parametritzable i modular.

Requisits del generador
Has de crear una funció principal i totes les subfuncions necessàries per:

  - Generar contrasenyes de longitud variable.
  - Decidir si han d'incloure:
    - Majúscules
    - Minúscules
    - Números
    - Signes especials
  - Assegurar-te que com a mínim apareix un caràcter de cada tipus seleccionat.
  - Aleatoritzar completament la contrasenya.
  - Retornar la contrasenya generada.

Nota important

Explora el funcionament del mòdul random de la llibreria icona enllaç numpy

La funció principal del generador ha de tenir valors per defecte, exactament els següents:

    majuscules=True
    minuscules=True
    numeros=True
    signes=False
Aquests paràmetres són obligatoris i formen part del disseny del sistema.

In [ ]:
import string

In [ ]:
import numpy as np

In [ ]:
def definir_longitud():
  """
  Función donde se solicita la longitud de la contraseña, número entero entre
  el 6 y el 12 y se comprueba que este dentro de los valores.

  No recibe argumentos.
  Retorna número entero en la variable longitud
  """
  print(
      'Bienvenido a la aplicación de creación de contraseñas.\n'
      'La contraseña debe tener, como mínimo, un caracter en mayusculas, minuscula, número y caracter especial.'
      '\nPasaremos a determinar la longitud de la contraseña, ha de ser como mínimo de 6 caracteres.\n')

  longitud_str = input("Quiere una longitud determinada de su nueva contraseña?\n")
  while True:
    try:
      if not longitud_str.isdigit():
        raise ValueError(
            f"Error en formato: El valor '{longitud_str}' no es válido, debe de ser un número entero."
        )

      longitud = int(longitud_str)

      if longitud < 6:
        raise ValueError(
            f"Error en la longitd: La contraseña no puede tener {longitud} caracteres.\nDebe tener entre 6 y 12 caracteres"
        )
      if longitud > 12:

        raise ValueError(
            f"Error en la longitd: La contraseña no puede tener {longitud} caracteres.\nDebe tener entre 6 y 12 caracteres"
        )
      print(f"\nLa longitud de su contraseña será de {longitud} caracteres.\n")
      break

    except ValueError as e:
      print(f"\n{e}")
      longitud_str = input("\nPor favor, facilite un número entero entre 6 y 12 para establecer la longitud de su contraseña.\n")

  return longitud

In [ ]:
def definir_caracteres():
  """
  Función que solicita si se quieren carateres en mayuscula, minuscula, números
  y carácteres especiales mediante la función definir boolenado.
  Obliga que como se quiera un tipo de caracter.

  No recibe argumentos
  Retorna valores booleanos para las variables:
  mayusculas, minusculas, numeros, caracteres_especiales
  """

  while True:

    mayusculas = definir_booleano("mayusculas")
    minusculas = definir_booleano("minusculas")
    numeros = definir_booleano("numeros")
    caracteres_especiales = definir_booleano("caracteres especiales")

    if any([mayusculas, minusculas, numeros, caracteres_especiales]):
        break
    print("\nDebe seleccionar al menos un tipo de carácter.\n")


  return mayusculas, minusculas, numeros, caracteres_especiales

In [ ]:
def definir_booleano(categoria):
  """
  Gestiona la respuesta de si se quiere o no los caracteres especiales

  Argumento recibido: Categoría de tipo de dato a definir en la contraseña.
  Retorna el valor booleano.
  """

  while True:
      respuesta = input(
      f"Quiere que la contraseña tenga {categoria}? (s/n).\n"
      ).strip().lower() #elimina espacios en blanco, covierte en minusculas el valor del input
      if respuesta in ("s", "n"):
        return respuesta == "s"
      print(f"\nValor introducido '{respuesta}' no valido.\n")#else

In [ ]:
def generar_contrasenya (longitud=12, mayusculas=True, minusculas=True, numeros=True, signos=False):
  """
  Función que genera una constraseña aleatoria con mayusculas, minusculas,
  números y caracteres especiales segun una longitud y cantidad de caracteres
  dada por el usuario. Se comprueba que como mínimo hay un caracter de cada y
  devuelve la contraseña al usuario.

  Argumentos recibidos:
    1. Valor número entero de la longitud de la contraseña.
    2. Valores booleanos de mayusculas, minusculas, numeros, caracteres_especiales
  Retorna los caracter generados aleatoriamente unidos en una variable (contraseña).
  """

  caracteres = ""
  caracteres_obligatorios = []
  if mayusculas:
    caracteres += string.ascii_uppercase
    caracteres_obligatorios += ''.join(np.random.choice(list(string.ascii_uppercase)))
  if minusculas:
    caracteres += string.ascii_lowercase
    caracteres_obligatorios += ''.join(np.random.choice(list(string.ascii_lowercase)))
  if numeros:
    caracteres += string.digits
    caracteres_obligatorios += ''.join(np.random.choice(list(string.digits)))
  if signos:
    caracteres += string.punctuation
    caracteres_obligatorios += ''.join(np.random.choice(list(string.punctuation)))

  contrasenya = [np.random.choice(list(caracteres)) for i in (range(longitud - len(caracteres_obligatorios)))]

  contrasenya_final = caracteres_obligatorios + contrasenya
  np.random.shuffle(contrasenya_final)

  return "".join(contrasenya_final)

In [ ]:
def nueva_contrasenya ():
  """
  Función que recoge el resto de funciones y devuelve la nueva contraseña.

  No recibe argumentos.
  Retorna la contraseña
  """

  longitud = definir_longitud()
  mayus, minus, num, sig = definir_caracteres()
  contra = generar_contrasenya(longitud, mayus, minus, num, sig)

  return contra

In [ ]:
print(nueva_contrasenya())

Bienvenido a la aplicación de creación de contraseñas.
La contraseña debe tener, como mínimo, un caracter en mayusculas, minuscula, número y caracter especial.
Pasaremos a determinar la longitud de la contraseña, ha de ser como mínimo de 6 caracteres.

Quiere una longitud determinada de su nueva contraseña?
11

La longitud de su contraseña será de 11 caracteres.

Quiere que la contraseña tenga mayusculas? (s/n).
s
Quiere que la contraseña tenga minusculas? (s/n).
s
Quiere que la contraseña tenga numeros? (s/n).
s
Quiere que la contraseña tenga caracteres especiales? (s/n).
s
y'2?-X8af/F

###**Ejercicio 2**

**Processament automàtic de dades esportives**

Ara formes part d'un equip d'analítica dins una organització esportiva que gestiona dades de la lliga catalana. La teva companya de feina vol automatitzar la lectura del seu arxiu històric de resultats i extreure les estadístiques més importants. T'ha demanat fer un petit sistema en Python que processi el fitxer

"historic partits.txt"

 Objectius

Mitjançant un codi modular, clar i documentat, el teu programa ha de calcular:

» 1.Quin equip és el més golejador.

» 2.Quin és el més golejat.

» 3.El nombre total de gols que ha fet cada equip.

» 4.La classificació final ordenada per punts on cada victòria suma 3 pts, cada empat 1 pts y cada derrota 0 pts.

En aquest nivell no es dona cap funció. Ets tu qui ha de dissenyar un flux complet. El codi ha de reflectir una bona organització interna.

In [ ]:
import pandas as pd

**ESTRUCTURA DE LAS FUNCIONES**
1. Función que recoge la ruta del fichero en parametro, se encarga de abrirlo y lo guarda en una lista ya limpia. Convierte la informacion de cada partido en una lista. Retorna lista

2. Funcion que recoge la lista limpia y la convierte en un DF, estableciendo el nombre de las columans (campos). Retrorna DF.

3. Funcion que toma el DF y calcula los puntos, victorias, empates y perdidas. Devuelve DF ampliado.

4. Funcion que recoge ese DF ampliado y agrupa resultados por equipo. Se realizan sumas finales para tener en cuenta los datos tanto de ida como de vuelta. Devuelve DF con los resultados sumados y agrupados.
Aqui tambien se muestra DF. SOLO SE GRUPA

5. Se suman los datos agrupados para obtener los resultados de los equipos, tanto jungando en casa como fuera.

6. Funcion que recoge DF agrupado, se encarga de responder las preguntas. Muestra resultados

++ Funcion que orquestra todas las demas

In [ ]:
def preparacion_archivo (ruta):
  """
  Función que se encarga de abrir el archivo de texto,
  limpiarlo y dejarlo en formato lista  para que se pueda convertir en DF.

  Argumento recibido: Variable con la ruta del archivo que se tiene que leer.
  Retorna lista de listas generada.
  """

  with open(ruta, 'rt', encoding='utf-8') as fichero:#se abre fichero
    lista_fichero = fichero.readlines()#se lee como lista

  lista_partidos =[]

  for elemento in lista_fichero: #se trata cada elemento de la lista
    partido = elemento.replace('\n', '').replace('-','\t').split('\t')#elimino \n, sustituyo el guión de los puntos por \t y se separan por\t
    partido[1] = int(partido[1])
    partido[2] = int(partido[2])
    lista_partidos.append(partido)#Se crea lista de listas

  return lista_partidos

In [ ]:
def conversion_lista_df (lista_partidos):
  """
  Función que toma la lista de partidos, ya limpios y la convierte en un DF.
  Estableciendo nombres de columnas.

  Argumento recibido: Lista de lista de listas con la info de cada partido.
  Retorna el df de la lista de listas.
  """

  columnas_partidos= ["equipo_local", "puntuacion_equipo_local","puntuacion_equipo_invitado","equipo_invitado"]

  df_partidos = pd.DataFrame(lista_partidos, columns=(columnas_partidos))

  return df_partidos

In [ ]:
def ampliar_datos_df (df_partidos):
  """
  Función que recoge el df bruto y añade valores por las victorias, empates,
  perdidas y puntos según estas circunstancias. Tanto para el equipo que juega
  en casa como el invitados.

  Argumento recibido: Df con los partidos.
  Retorna df con datos ampliados en los partidos.
  """

  for i, partido in df_partidos.iterrows():
    if partido['puntuacion_equipo_local'] > partido['puntuacion_equipo_invitado']:
      df_partidos.loc[i, 'puntos_local'] = 3
      df_partidos.loc[i, 'local_ganador'] = 1
      df_partidos.loc[i, 'visitante_perdedor'] = 1

    elif partido['puntuacion_equipo_local'] == partido['puntuacion_equipo_invitado']:
      df_partidos.loc[i, 'puntos_local'] = 1
      df_partidos.loc[i, 'puntos_visitante'] = 1
      df_partidos.loc[i, 'local_empate'] = 1
      df_partidos.loc[i, 'visitante_empate'] = 1

    else:
      df_partidos.loc[i, 'puntos_visitante'] = 3
      df_partidos.loc[i, 'local_perdedor'] = 1
      df_partidos.loc[i, 'visitante_ganador'] = 1

  return df_partidos

In [ ]:
def agrupacion_datos (df_partidos):
  """
  Función que agrupa los resultados y metricas derivadas.
  Devuelve dos  df con los datos de los equipos agrupados, uno con los resultados
  conseguidos jugando en casa y el otro como de invitado.

  Argumento recibido: df partidos con datos ampliados.
  Retorna dos dataframes, agrupando la información por equipo si jugaba en local
  o si jugaba como visitante
  """
  #datos equipo como local:
  df_agrupado_local = df_partidos.groupby('equipo_local')[
    ['puntuacion_equipo_local', #para ver cuantos goles han marcado
     'puntuacion_equipo_invitado', #para ver cuantos goles le han marcado
     'puntos_local',
     'local_ganador',
     'local_empate',
     'local_perdedor']].sum()

  #datos equipo como invitado:
  df_agrupado_invitado = df_partidos.groupby('equipo_invitado')[
    ['puntuacion_equipo_invitado', #para ver cuantos goles han marcado
     'puntuacion_equipo_local', #para ver cuantos goles les han marcado
     'puntos_visitante',
     'visitante_ganador',
     'visitante_empate',
     'visitante_perdedor']].sum()

  return df_agrupado_local, df_agrupado_invitado

In [ ]:
def suma_datos (df_agrupado_local, df_agrupado_invitado):
  """
  Función que suma los resultados tanto de ida como de vuelta por cada equipo.

  Argumentos recibidos: Dos DataFrames con los datos agrupados por equipo
  uno si jugaba en local y el otro si jugaba como invitado.
  Devuelve un único DF
  """
  df_respuestas = df_agrupado_local['puntuacion_equipo_local'] + df_agrupado_invitado['puntuacion_equipo_invitado'] #el primero sale como serie
  df_respuestas.rename_axis('equipos', inplace=True)
  df_respuestas.rename('goles_a_favor', inplace=True) #se reenombra antes de convertir la serie en DF porque es mas sencillo
  df_respuestas = df_respuestas.to_frame()#convierto la serie en DF
  df_respuestas['goles_en_contra'] = df_agrupado_local['puntuacion_equipo_invitado'] + df_agrupado_invitado['puntuacion_equipo_local']
  df_respuestas['puntos_totales'] = df_agrupado_local['puntos_local'] + df_agrupado_invitado['puntos_visitante']
  df_respuestas['partidos_ganados'] = df_agrupado_local['local_ganador'] + df_agrupado_invitado['visitante_ganador']
  df_respuestas['partidos_empatados'] = df_agrupado_local['local_empate'] + df_agrupado_invitado['visitante_empate']
  df_respuestas['partidos_perdidos'] = df_agrupado_local['local_perdedor'] + df_agrupado_invitado['visitante_perdedor']

  return df_respuestas

In [ ]:
def resultados (df_respuestas):
  """
  Función que devuelve los resultados a las preguntas solicitadas:
  1. Equipo que más goles a marcado.
  2. Equipo al que más goles han marcado.
  3. Devuelve el DF ordenado por los puntos conseguidos de mayor a menor.

  Argumento recibido: DataFrame con los totales por equipo
  Retorna el DataFrame ordenado por los puntos de mayor a menor
  """
  #1. Devuelve el valor del indice donde se confirma el equipo con la maxima cantidad de goles realizados.
  equipo_mas_goles = df_respuestas['goles_a_favor'].idxmax()
  print("Pregunta 1: Que equipo ha marcado más goles?\n")
  print(f"El equipo que más goles ha marcado es: {equipo_mas_goles}.\n\n")

  #2. Devuelve el valor del indice donde se confirma el equipo con la maxima cantidad de goles recibados.
  equipo_mas_goleado = df_respuestas['goles_en_contra'].idxmax()
  print("Pregunta 2: A qué equipo han marcado más goles?\n")
  print(f"El equipo al que han marcado más goles es: {equipo_mas_goleado}.\n\n")

  #3. Se ordena DF por los puntos totales en orden descendente.
  print("Pregunta 3: Clasificación de los equipos según puntuación total:\n")
  df_final_ordenado =df_respuestas.sort_values(by=['puntos_totales'], ascending=False)
  display(df_final_ordenado)

  return df_final_ordenado

In [ ]:
def analisis_partidos (ruta):
  """
  Funcion que orquestra todas las funciones necesarias para analizar
  los resultados de los partidos.

  Argumento recibido la ruta del archivo para leer.
  Retorna el DF ordenado por la cantidad de puntos realizados.
  """
  lista_partidos = preparacion_archivo(ruta)
  df_inicio = conversion_lista_df(lista_partidos)
  df_ampliado = ampliar_datos_df(df_inicio)
  df_agrupado_loc, df_agrupado_inv = agrupacion_datos(df_ampliado)
  df_final = suma_datos(df_agrupado_loc, df_agrupado_inv)
  df_final_ordenado = resultados(df_final)

  return df_final_ordenado

In [ ]:
ruta = '/content/drive/MyDrive/Colab Notebooks/historic_partits.txt'
analisis_partidos(ruta)

Pregunta 1: Que equipo ha marcado más goles?

El equipo que más goles ha marcado es: Figueres.


Pregunta 2: A qué equipo han marcado más goles?

El equipo al que han marcado más goles es: Vilafranca.


Pregunta 3: Clasificación de los equipos según puntuación total:

,goles_a_favor,goles_en_contra,puntos_totales,partidos_ganados,partidos_empatados,partidos_perdidos
equipos,,,,,,
Girona FC,139,94,96.0,31.0,3.0,13.0
Llagostera,159,142,94.0,29.0,7.0,20.0
Sabadell,141,121,85.0,26.0,7.0,15.0
Cornellà,147,146,82.0,25.0,7.0,22.0
RCD Espanyol,131,144,80.0,23.0,11.0,21.0
Figueres,161,154,79.0,23.0,10.0,23.0
Lleida Esportiu,129,133,75.0,23.0,6.0,23.0
Terrassa,147,164,74.0,20.0,14.0,23.0
FC Barcelona,125,115,73.0,22.0,7.0,15.0
Vilafranca,157,172,72.0,20.0,12.0,25.0
Badalona,134,124,68.0,18.0,14.0,16.0
Reus Deportiu,119,111,68.0,20.0,8.0,16.0
Nàstic de Tarragona,130,148,68.0,20.0,8.0,27.0
Granollers,122,117,67.0,21.0,4.0,24.0
Olot,132,144,64.0,18.0,10.0,26.0
Sant Andreu,123,134,62.0,17.0,11.0,25.0
Manlleu,106,118,57.0,16.0,9.0,18.0
Cerdanyola,117,133,56.0,17.0,5.0,28.0
Prat,106,111,56.0,16.0,8.0,21.0
Europa,93,93,41.0,12.0,5.0,16.0